-- ================================================================
-- UADED — Sistema de Gestión Educativa
-- Script de creación de base de datos PostgreSQL 12+
-- ================================================================

-- Crear rol de base de datos (ejecutar como superusuario)
-- Si el rol ya existe, comentar esta línea:
CREATE ROLE uaded WITH INHERIT LOGIN ENCRYPTED PASSWORD 'uaded123';

-- Crear base de datos
CREATE DATABASE uaded_db OWNER uaded ENCODING 'UTF8';

-- Conectarse a la base de datos antes de ejecutar el resto:
-- \c uaded_db

-- ── Secuencias ────────────────────────────────────────────────
CREATE SEQUENCE public.usr_id_seq  INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1;
CREATE SEQUENCE public.rol_id_seq  INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1;
CREATE SEQUENCE public.per_id_seq  INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1;

-- ── Usuarios / Roles / Permisos ───────────────────────────────
CREATE TABLE public.usuario (
    id         integer      NOT NULL DEFAULT nextval('public.usr_id_seq'),
    usuario    varchar(80)  NOT NULL,
    email      varchar(100) NOT NULL,
    password   varchar(255) NOT NULL,
    activo     boolean,
    last_login date         NOT NULL,
    creado     timestamp,
    act        timestamp,
    CONSTRAINT usr_pkey PRIMARY KEY (id)
);
ALTER TABLE public.usuario OWNER TO uaded;
CREATE UNIQUE INDEX ix_usr_usuario ON public.usuario USING btree (usuario) WITH (fillfactor=90);

CREATE TABLE public.rol (
    id          integer      NOT NULL DEFAULT nextval('public.rol_id_seq'),
    rol         varchar(50)  NOT NULL,
    descripcion varchar(255),
    creado      timestamp,
    act         timestamp,
    CONSTRAINT rol_pkey PRIMARY KEY (id),
    CONSTRAINT rol_rol_key UNIQUE (rol)
);
ALTER TABLE public.rol OWNER TO uaded;

CREATE TABLE public.permiso (
    id          integer      NOT NULL DEFAULT nextval('public.per_id_seq'),
    permiso     varchar(50)  NOT NULL,
    descripcion varchar(255),
    creado      timestamp,
    act         timestamp,
    CONSTRAINT per_pkey PRIMARY KEY (id),
    CONSTRAINT per_permiso_key UNIQUE (permiso)
);
ALTER TABLE public.permiso OWNER TO uaded;

CREATE TABLE public.usuario_rol (
    usu_id integer NOT NULL,
    rol_id integer NOT NULL,
    CONSTRAINT usr_rol_pkey PRIMARY KEY (usu_id, rol_id)
);
ALTER TABLE public.usuario_rol OWNER TO uaded;

CREATE TABLE public.rol_permiso (
    rol_id integer NOT NULL,
    per_id integer NOT NULL,
    CONSTRAINT rol_per_pkey PRIMARY KEY (rol_id, per_id)
);
ALTER TABLE public.rol_permiso OWNER TO uaded;

-- ── Módulo académico ──────────────────────────────────────────
CREATE TABLE public.gestion (
    id      integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    gestion smallint,
    plan    varchar(150) NOT NULL,
    inicio  date         NOT NULL,
    fin     date         NOT NULL,
    activo  boolean      NOT NULL,
    creado  timestamp         NOT NULL,
    act     timestamp         NOT NULL,
    usu_id  integer      NOT NULL,
    CONSTRAINT ges_pk PRIMARY KEY (id)
);
ALTER TABLE public.gestion OWNER TO uaded;

CREATE TABLE public.grado (
    id     integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    grado  varchar(255) NOT NULL,
    nivel  varchar(150) NOT NULL,
    ges_id integer      NOT NULL,
    creado timestamp         NOT NULL,
    act    timestamp         NOT NULL,
    usu_id integer      NOT NULL,
    CONSTRAINT gra_pkey PRIMARY KEY (id)
);
ALTER TABLE public.grado OWNER TO uaded;

CREATE TABLE public.materia (
    id      integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    materia varchar(150) NOT NULL,
    gra_id  integer      NOT NULL,
    creado  timestamp         NOT NULL,
    act     timestamp         NOT NULL,
    usu_id  integer      NOT NULL,
    CONSTRAINT mat_pkey PRIMARY KEY (id)
);
ALTER TABLE public.materia OWNER TO uaded;

CREATE TABLE public.profesor (
    id           integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nombre       varchar(100) NOT NULL,
    paterno      varchar(50),
    materno      varchar(50),
    masculino    boolean      NOT NULL,
    ci           integer,
    formacion    varchar(100),
    email        varchar(100),
    activo       boolean      NOT NULL,
    usr_id_login integer,
    creado       timestamp         NOT NULL,
    act          timestamp         NOT NULL,
    usu_id       integer      NOT NULL,
    CONSTRAINT pro_pk PRIMARY KEY (id)
);
ALTER TABLE public.profesor OWNER TO uaded;

CREATE TABLE public.curso (
    id        integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    curso     varchar(150),
    paralelo  varchar(50)  NOT NULL,
    gra_id    integer      NOT NULL,
    aula      varchar(50),
    capacidad smallint,
    gestion   smallint     NOT NULL,
    creado    timestamp         NOT NULL,
    act       timestamp         NOT NULL,
    usu_id    integer      NOT NULL,
    CONSTRAINT cur_pk PRIMARY KEY (id)
);
ALTER TABLE public.curso OWNER TO uaded;

CREATE TABLE public.asignado (
    id     integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cur_id integer NOT NULL,
    mat_id integer NOT NULL,
    pro_id integer NOT NULL,
    creado timestamp    NOT NULL,
    act    timestamp    NOT NULL,
    usu_id integer NOT NULL,
    CONSTRAINT asi_pk PRIMARY KEY (id)
);
COMMENT ON TABLE public.asignado IS 'Profesor asignado a un curso y materias';
ALTER TABLE public.asignado OWNER TO uaded;

CREATE TABLE public.alumno (
    id           integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nombre       varchar(100) NOT NULL,
    paterno      varchar(100),
    materno      varchar(100),
    nacimiento   date,
    masculino    boolean      NOT NULL,
    ci           integer,
    direccion    varchar(150),
    email        varchar(100),
    activo       boolean      NOT NULL,
    obs          varchar(100),
    usr_id_login integer,
    foto_ruta    varchar(150),
    creado       timestamp         NOT NULL,
    act          timestamp         NOT NULL,
    usu_id       integer      NOT NULL,
    CONSTRAINT alu_pk PRIMARY KEY (id)
);
ALTER TABLE public.alumno OWNER TO uaded;

CREATE TABLE public.inscrito (
    id               integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    alu_id           integer,
    cur_id           integer,
    reserva          boolean,
    inscrito         boolean      NOT NULL,
    descuento        smallint     NOT NULL DEFAULT 0,
    motivo_descuento varchar(100),
    abandono         boolean      NOT NULL DEFAULT false,
    obs              varchar(200),
    creado           timestamp         NOT NULL,
    act              timestamp         NOT NULL,
    usu_id           integer      NOT NULL,
    CONSTRAINT ins_pk  PRIMARY KEY (id),
    CONSTRAINT ins_uq  UNIQUE (alu_id)
);
COMMENT ON TABLE  public.inscrito IS 'Alumno inscrito en un curso';
COMMENT ON COLUMN public.inscrito.descuento IS '% de descuento sobre la cuota';
ALTER TABLE public.inscrito OWNER TO uaded;

CREATE TABLE public.nota (
    id         integer        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ins_id     integer        NOT NULL,
    mat_id     integer        NOT NULL,
    nota1      smallint       NOT NULL DEFAULT 0,
    nota2      smallint       NOT NULL DEFAULT 0,
    nota3      smallint       NOT NULL DEFAULT 0,
    nota_final numeric(5,1)   NOT NULL DEFAULT 0,
    nota_aprob smallint       NOT NULL DEFAULT 51,
    aprobado   boolean,
    obs        varchar(150),
    creado     timestamp           NOT NULL,
    act        timestamp           NOT NULL,
    usu_id     integer        NOT NULL,
    CONSTRAINT cal_pk PRIMARY KEY (id)
);
COMMENT ON TABLE public.nota IS 'Seguimiento académico por materia';
ALTER TABLE public.nota OWNER TO uaded;

CREATE TABLE public.costo (
    id        integer        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cur_id    integer        NOT NULL,
    nro_cuota smallint       NOT NULL,
    cuota     numeric(10,2)  NOT NULL,
    obs       varchar(200)   NOT NULL,
    creado    timestamp           NOT NULL,
    act       timestamp           NOT NULL,
    usu_id    integer        NOT NULL,
    CONSTRAINT cos_pk PRIMARY KEY (id)
);
ALTER TABLE public.costo OWNER TO uaded;

CREATE TABLE public.pago (
    id              integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ins_id          integer      NOT NULL,
    nro_cuota       smallint     NOT NULL,
    cuota           double precision NOT NULL,
    pagado          boolean      DEFAULT false,
    metodo_pago     varchar(50),
    fecha_pago      timestamp,
    referencia_pago varchar(100),
    obs             varchar(100),
    creado          timestamp         NOT NULL,
    act             timestamp         NOT NULL,
    usu_id          integer      NOT NULL
);
ALTER TABLE public.pago OWNER TO uaded;

-- ── Llaves Foráneas ───────────────────────────────────────────
ALTER TABLE public.grado     ADD CONSTRAINT ges_fk     FOREIGN KEY (ges_id) REFERENCES public.gestion(id)  ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.materia   ADD CONSTRAINT mat_gra_fk FOREIGN KEY (gra_id) REFERENCES public.grado(id)    ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.curso     ADD CONSTRAINT gra_fk     FOREIGN KEY (gra_id) REFERENCES public.grado(id)    ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.asignado  ADD CONSTRAINT pro_fk     FOREIGN KEY (pro_id) REFERENCES public.profesor(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.asignado  ADD CONSTRAINT cur_fk     FOREIGN KEY (cur_id) REFERENCES public.curso(id)    ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.asignado  ADD CONSTRAINT mat_fk     FOREIGN KEY (mat_id) REFERENCES public.materia(id)  ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.inscrito  ADD CONSTRAINT alu_fk     FOREIGN KEY (alu_id) REFERENCES public.alumno(id)   ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.inscrito  ADD CONSTRAINT cur_fk     FOREIGN KEY (cur_id) REFERENCES public.curso(id)    ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.nota      ADD CONSTRAINT ins_fk     FOREIGN KEY (ins_id) REFERENCES public.inscrito(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.costo     ADD CONSTRAINT cur_fk     FOREIGN KEY (cur_id) REFERENCES public.curso(id)    ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.pago      ADD CONSTRAINT insc_fk    FOREIGN KEY (ins_id) REFERENCES public.inscrito(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE public.usuario_rol ADD CONSTRAINT usr_rol_usr_fk FOREIGN KEY (usu_id) REFERENCES public.usuario(id);
ALTER TABLE public.usuario_rol ADD CONSTRAINT usr_rol_rol_fk FOREIGN KEY (rol_id) REFERENCES public.rol(id);
ALTER TABLE public.rol_permiso ADD CONSTRAINT rol_per_rol_fk FOREIGN KEY (rol_id) REFERENCES public.rol(id);
ALTER TABLE public.rol_permiso ADD CONSTRAINT rol_per_per_fk FOREIGN KEY (per_id) REFERENCES public.permiso(id);

-- ── Conceder privilegios al rol uaded ────────────────────────
GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA public TO uaded;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO uaded;
